name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build_package:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v6
              with:
                python-version: ${{ matrix.python-version }}
                cache: 'pip'
                cache-dependency-path: requirements.txt

            - name: Install build tools
              run: |
                python -m pip install --upgrade pip
                pip install build

            - name: Build wheel
              run: python -m build --wheel

            - name: Upload wheel artifact
              uses: actions/upload-artifact@v4
              with:
                name: greeting-wheel-${{ matrix.python-version }}
                path: dist/*.whl

    unit_test:
        runs-on: ubuntu-latest
        needs: build_package
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v6
              with:
                python-version: ${{ matrix.python-version }}
                cache: 'pip'
                cache-dependency-path: requirements.txt

            - name: Download wheel artifact
              uses: actions/download-artifact@v4
              with:
                name: greeting-wheel-${{ matrix.python-version }}
                path: dist

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Install wheel package
              run: pip install dist/*.whl

            - name: Analyser la syntaxe avec flake8
              run: flake8 $(git ls-files '*.py')

            - name: Tests avec pytest et coverage + rapport HTML
              run: pytest --cov=greeting --cov-fail-under=90 --cov-report=html tests/

            - name: Upload du rapport de couverture HTML
              uses: actions/upload-artifact@v4
              with:
                name: coverage-html-${{ matrix.python-version }}
                path: htmlcov/
