---
- hosts: apps
  vars_files:
    - group_vars/apps.yml

  tasks:
    - name: Create app directory
      file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'

    - name: Login to Docker registry
      docker_login:
        registry: "{{ registry }}"
        username: "{{ registry_login }}"
        password: "{{ registry_password }}"

    - name: Copy and template docker-compose.yml
      template:
        src: docker-compose.yml
        dest: "{{ app_directory }}/docker-compose.yml"
      tags: template

    - name: Copy and template backend.env
      template:
        src: backend.env
        dest: "{{ app_directory }}/backend.env"
      tags: template

    - name: Stop and remove old containers (if exist)
      shell: docker compose down --remove-orphans
      args:
        chdir: "{{ app_directory }}"
      ignore_errors: true

    - name: Pull Docker images
      shell: docker compose pull
      args:
        chdir: "{{ app_directory }}"

    - name: Start containers
      shell: docker compose up -d --remove-orphans
      args:
        chdir: "{{ app_directory }}"
