name: Deploy reusable workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "Environnement cible (dev, test, prod)"
        required: true
        type: string
      image_tag:
        description: "Tag de l'image Docker (commit SHA)"
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      DOCKER_LOGIN:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_REGISTRY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: ${{ inputs.environment }}
    concurrency:
      group: deploy-${{ inputs.environment }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          # Installation rapide sans mise à jour du cache si Ansible est déjà présent
          if ! command -v ansible-playbook &> /dev/null; then
            sudo apt-get update -q
            sudo apt-get install -y ansible
          else
            echo "Ansible is already installed"
          fi

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 62222 -H dev22.iut.arcanit.io >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini deploy.yml \
            -e "app_environment=${{ inputs.environment }}" \
            -e "app_directory=/home/student/apps/niveau-samuel-${{ inputs.environment }}" \
            -e "registry=${{ secrets.DOCKER_REGISTRY }}" \
            -e "registry_login=${{ secrets.DOCKER_LOGIN }}" \
            -e "registry_password=${{ secrets.DOCKER_PASSWORD }}" \
            -e "image_tag=${{ inputs.image_tag }}" \
            -e "environment_prefix=${{ inputs.environment == 'prod' && '' || format('{0}-', inputs.environment) }}"
