name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    environment: docker   # <-- ton environnement Docker
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/niveau-samuel-backend:latest
            ${{ secrets.DOCKER_REGISTRY }}/niveau-samuel-backend:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    environment: docker   # <-- idem
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/web.dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/niveau-samuel-frontend:latest
            ${{ secrets.DOCKER_REGISTRY }}/niveau-samuel-frontend:${{ github.sha }}
